### PR TITLE
AD8403 Ready

### PR DESCRIPTION
**Pull request by Ale11Re**
changed SPI_MODE1 to SPI_MODE0
changed Reset, Shutdown logic
changed demo example

### CODE REVIEW

**Comment by RobTillaart** [comment]
@Ale11Re 
Thanks for the issues and the PR, I will look at them today.

**Comment by RobTillaart** [comment]
verified the documentation and merged your code.
Thanks again, I will update the version to 0.3.0  (going to add RP2040 in build support too)

**Comment by RobTillaart** [comment]
@Ale11Re 
Could you verify if the software SPI does works as intended (I assume you have some hardware nearby)
Thanks for your time.

**Comment by RobTillaart** [comment]
Thanks for verifying.
I have to check if I have a spare to make a test setup.
Otherwise I need to order one.

Just to know, what board do you use?

**Comment by RobTillaart** [comment]
No chip available, ordered - https://nl.rs-online.com/web/p/power-motor-robotics-development-tools/2475645 
(not cheap but looks easy to test)

**Comment by Ale11Re** [comment]
I'm using an arduino mega2560. I could also verify ESP32 VSPI but not HSPI as I only have 1 model which has HSPI already in use.
I only have one AD8403 lying around.
I used an oscilloscope to very sawtooth and sinusoidal wave and as you mentioned, software SPI is about 15 times slower than hardware SPI.
Just to clarify: this is my first contribution in github, I believe I understood how this platform works so if I made a mistake, please let me know.

**Comment by RobTillaart** [comment]
Your contribution is super 👍 really appreciated.
I have written a lot of libraries in past decade and are not able to test all possible configurations. 
Some are even only tested by others 

I am interested in the ESP32 VSPI and the software SPI. The latter is very fast on ESP32, in some other tests it was roughly on par with hardware SPI. The SW SPI pulses are slightly slower thus longer, but SW SPI has not the transaction overhead. In fact this results in nicer square waves with the SW SPI. It would be nice if confirmed here too.

**Comment by Ale11Re** [comment]
So, as I'm writing,  I'm testing HSPI and VSPI on ESP32 an they work as intended.
Software SPI works too but it's a bit slower:
1 tooth of the Sawtooth wave tooks about 4ms on HSPI and VSPI while on Software SPI 6.5 ms.
Just for reference, it's about 5 ms on the hardware SPI of AtMega2560 and 60ms on software SPI.

**Comment by RobTillaart** [comment]
Thanks for these numbers, they look good imho.

**Pull request merged**
